### ISSUE TITLE
Use HttpResponseCache (or similar) instead of reimplementing HTTP caching

### ISSUE THREAD

**Issue by candrews** [lexs/webimageloader#1]
I noticed that you reimplement HTTP caching (respecting etags and other headers) when Android 4.0 and later does this for you - see https://developer.android.com/reference/android/net/http/HttpResponseCache.html
To support versions of Android before 4.0, you could use my library: https://github.com/candrews/httpresponsecache

I only point this out as implementing these parts of the HTTP protocol aren't easy, and I haven't examined your code terribly closely, but I'd be willing to bet it isn't up to feature parity or have as few bugs as the Android implementation. You could probably save yourself a lot of maintenance headache by reusing a library for this.

**Comment by lexs** [comment]
I looked at your library when implementing cache invalidation but didn't copy any implementation (or use the library directly) because I'd like to keep this part simple. We don't really need to respect all cache headers as we don't want to, for example, revalidate the cache for every request. It currently only respects max-age/expires when checking on how to invalidate a request. While this part is pretty simple it would definitely be interesting to respect more headers in the future, maybe using ResponseHeaders.java from HttpResponseCache?

Using the library as-is won't work as we also want to be able to cache transformed bitmaps, making this work would require adding additional methods to the response cache (or keeping separate caches) which is not something I want to do.

**Comment by smarek** [comment]
Hi @lexs 
I don't think that implementing ETags (If-None-Match) or using If-Modified-Since is some kind of overhead, but I'd love to see the image being checked online in some time.

The period of checking should be configurable in load request/call (eg. if I don't want or cannot rely on server 'Expires' header)

**Comment by lexs** [comment]
@smarek I'm not sure what you are referring to? ETags and modified since is already implemented. You can also override max-age (but currently only globally).

**Comment by smarek** [comment]
So, in this case I'm sorry, I've probably overlooked something in code. Thanks for having this feature turned on :-)
