### ISSUE TITLE
Packages and Eclipse

### ISSUE THREAD

**Issue by matecode** [lexs/webimageloader#14]
Hi... if I try to import the code of the directory "webimagloader" in eclipse as a "excisting Code Android Project" i get errors because your package-declaration "com.webimageloader" does not fit your directory-structure "main.java.com.webimageloader". This is necessary for eclipse. I wonder if i'm doing something wrong or maybe dont know something. Why do you have this structure? Greets, Mate

**Comment by lexs** [comment]
The projects build is managed by Maven, that's why the directory structure is different. The easy way is probably to use the Eclipse Maven plugin and configurator, see here http://rgladwell.github.com/m2e-android/

An even easier way is to open the project using IntelliJ which has native support for Maven.
