### ISSUE TITLE
Create load function which retrieves the path to the file instead of a Bitmap

### ISSUE THREAD

**Issue by arnaudbos** [lexs/webimageloader#8]
How about creating a duplicate of the load function which would retrieve the URI path to the downloaded/cached file (or null) instead of a Bitmap instance ?

This would be neat to integrate you library into an image gallery (imageviews inside view pager) without putting all the bitmaps in memory.

**Comment by lexs** [comment]
I'm not sure what you want the use case is, showing the images inside a ViewPager would still require them loaded into memory? Please describe the use case in more detail, there may be a simpler way of solving it. One thing I want to do is support "flags" saying to do stuff like skip memory cache, or don't cache intermediate transformations etc.

Anyways, returning the File instead of Bitmap is hard because of two things.
1). The code which handles disk caching (DiskLruCache) doesn't have a method to expose the File, probably due to 2.
2). Even if a File was returned there is no guarantee that it will be there when you try to read it, another image may have triggered a purge of this image. concurrency is tricky that way.

Also, you won't always even have a disk cache.

**Comment by arnaudbos** [comment]
Sure, didn't think about the concurrency that way... The idea behind this "issue" opening was to use some sort of view holder pattern inside the view pager to load the image only when needed.
I guess a FragmentStatePagerAdapter would be more suitable, I don't know.

**Comment by lexs** [comment]
I think this could be handled by simple doing the load when the actual fragment is shown instead of when it's created. 

Even if you could retrieve a File, note that loading a bitmap from it is still a blocking operation.
